name = "immunasina"
main = "dist/index.js"

[site]
# The directory where your compiled assets are located
# This should point to your frontend build output directory
# For Vite, this is typically 'dist'
bucket = "./dist"
# The entry point for your Worker script
entry-point = "./worker-site/index.js"

compatibility_date = "2026-07-03"
compatibility_flags = ["nodejs_compat"]

# Tells Wrangler where your built frontend React HTML/CSS/JS files are located:
[assets]
directory = "./dist/public"
binding = "ASSETS"