name = "immunasina"
#main = "dist/index.js"
main = "worker-site/index.js"

compatibility_date = "2026-07-03"
compatibility_flags = ["nodejs_compat"]

# Tells Wrangler where your built frontend React HTML/CSS/JS files are located:
[assets]
directory = "./dist/public"
binding = "ASSETS"